modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="chickenbumblebee"
version="1.0.0"
displayName="CHICKENBUMBLEBEE"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="niceEli"

[[dependencies.chickenbumblebee]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




